### ISSUE TITLE
docker 镜像部署失败

### ISSUE THREAD

**Issue by juukee** [Tencent/cloudbase-framework#131]
docker 镜像部署失败
报错如下：
at SamManager.<anonymous> (C:\Users\Juukee\AppData\Roaming\npm\node_modules\@cloudbase\cli\node_modules\@cloudbase\framework-core\lib\sam\index.js:129:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Juukee\AppData\Roaming\npm\node_modules\@cloudbase\cli\node_modules\@cloudbase\framework-core\lib\sam\index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
×
部署失败，错误信息：[100003]+ docker build -f ./Dockerfile -t ccr.ccs.tencentyun.com/tcb-******-qdkp/fscz-faca0_jumpserver:jumpserver-005-1605629965 ./
Sending build context to Docker daemon  87.48MB

**Comment by binggg** [comment]
看起来是构建出错了，本地可以构建一下看看是否报错

**Comment by juukee** [comment]
初步定位为两个问题：
1.镜像拉取失败，云开发默认仓库为ccr，后续可能需要迁移到tcr，待确认
2.多端口开放，由于需要开放两个端口，默认云开发目前只能支持单端口

**Comment by binggg** [comment]
多端口开放等待产品规划，先关闭了
